# Generated by Django 3.1.5 on 2021-04-22 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matchplayers',
            unique_together={('match', 'player')},
        ),
    ]
