# Generated by Django 3.1.5 on 2021-04-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0002_auto_20210422_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchplayers',
            name='batted',
            field=models.BooleanField(default=False),
        ),
    ]
