# Generated by Django 3.1.5 on 2021-04-23 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cricket', '0003_matchplayers_batted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fanzy_players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='cricket.player')),
                ('player10', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player10', to='cricket.player')),
                ('player11', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player11', to='cricket.player')),
                ('player2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='cricket.player')),
                ('player3', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player3', to='cricket.player')),
                ('player4', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player4', to='cricket.player')),
                ('player5', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player5', to='cricket.player')),
                ('player6', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player6', to='cricket.player')),
                ('player7', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player7', to='cricket.player')),
                ('player8', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player8', to='cricket.player')),
                ('player9', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player9', to='cricket.player')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
