# Generated by Django 3.1.5 on 2021-04-23 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0004_fanzy_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanzy_players',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='cricket.player'),
        ),
        migrations.AlterField(
            model_name='fanzy_players',
            name='player10',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player10', to='cricket.player'),
        ),
        migrations.AlterField(
            model_name='fanzy_players',
            name='player11',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player11', to='cricket.player'),
        ),
        migrations.AlterField(
            model_name='fanzy_players',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='cricket.player'),
        ),
        migrations.AlterField(
            model_name='fanzy_players',
            name='player3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player3', to='cricket.player'),
        ),
        migrations.AlterField(
            model_name='fanzy_players',
            name='player4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player4', to='cricket.player'),
        ),
        migrations.AlterField(
            model_name='fanzy_players',
            name='player5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player5', to='cricket.player'),
        ),
        migrations.AlterField(
            model_name='fanzy_players',
            name='player6',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player6', to='cricket.player'),
        ),
        migrations.AlterField(
            model_name='fanzy_players',
            name='player7',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player7', to='cricket.player'),
        ),
        migrations.AlterField(
            model_name='fanzy_players',
            name='player8',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player8', to='cricket.player'),
        ),
        migrations.AlterField(
            model_name='fanzy_players',
            name='player9',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player9', to='cricket.player'),
        ),
    ]
